// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("BUSINESS_PROCESS", Schema = "bp")]
[Index("BusinessProcessCode", Name = "AK_BUSINESS_PROCESS", IsUnique = true)]
[Index("BusinessProcessTypeId", Name = "FK_BUSINESS_PROCESS_BusinessProcessTypeID")]
public partial class BusinessProcess
{
    [Key]
    [Column("BusinessProcessID")]
    public short BusinessProcessId { get; set; }

    [Required]
    [StringLength(7)]
    [Unicode(false)]
    public string BusinessProcessCode { get; set; }

    [Required]
    [StringLength(150)]
    public string BusinessProcessNameCyr { get; set; }

    [Required]
    [StringLength(150)]
    public string BusinessProcessNameLat { get; set; }

    [Required]
    [StringLength(150)]
    public string BusinessProcessNameEng { get; set; }

    [Required]
    [StringLength(500)]
    public string BusinessProcessDescription { get; set; }

    [Column("BusinessProcessFileBPMN", TypeName = "xml")]
    public string BusinessProcessFileBpmn { get; set; }

    [Column("BusinessProcessTypeID")]
    public byte BusinessProcessTypeId { get; set; }

    public bool BusinessProcessIsActive { get; set; }

    [Required]
    [Column("RoleTypeIDs")]
    [StringLength(18)]
    [Unicode(false)]
    public string RoleTypeIds { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [Column("NotificationEndCC")]
    [StringLength(255)]
    [Unicode(false)]
    public string NotificationEndCc { get; set; }

    [InverseProperty("BusinessProcess")]
    public virtual ICollection<BusinessProcessStep> BusinessProcessSteps { get; set; } = new List<BusinessProcessStep>();

    [InverseProperty("BusinessProcess")]
    public virtual ICollection<ServiceDef> ServiceDefs { get; set; } = new List<ServiceDef>();
}