// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("BUSINESS_PROCESS_STEP", Schema = "bp")]
[Index("BusinessProcessId", Name = "FK_BUSINESS_PROCESS_STEP_BusinessProcessTypeID")]
public partial class BusinessProcessStep
{
    [Key]
    [Column("BusinessProcessStepID")]
    public short BusinessProcessStepId { get; set; }

    [Column("BusinessProcessID")]
    public short BusinessProcessId { get; set; }

    [Column("BusinessProcessStepTypeID")]
    public byte BusinessProcessStepTypeId { get; set; }

    [Required]
    [StringLength(150)]
    public string BusinessProcessStepNameLat { get; set; }

    [Required]
    [StringLength(500)]
    public string BusinessProcessStepDescription { get; set; }

    [Required]
    [StringLength(2)]
    [Unicode(false)]
    public string BusinessProcessStepOrder { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public bool IsSendEndUserNotification { get; set; }

    public bool IsSendNotification { get; set; }

    [Column("NotificationTemplateTypeID")]
    public byte? NotificationTemplateTypeId { get; set; }

    [ForeignKey("BusinessProcessId")]
    [InverseProperty("BusinessProcessSteps")]
    public virtual BusinessProcess BusinessProcess { get; set; }

    [InverseProperty("BussinesProcessStep")]
    public virtual ICollection<CaseWorkflow> CaseWorkflows { get; set; } = new List<CaseWorkflow>();

    [InverseProperty("BussinesProcessStep")]
    public virtual ICollection<Case> Cases { get; set; } = new List<Case>();

    [InverseProperty("BussinesProcessStep")]
    public virtual ICollection<DocumentWorkflow> DocumentWorkflows { get; set; } = new List<DocumentWorkflow>();
}