// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[PrimaryKey("CaseId", "EntityId")]
[Table("CASE_ENTITY", Schema = "algo")]
public partial class CaseEntity
{
    [Key]
    [Column("CaseID")]
    public int CaseId { get; set; }

    [Key]
    [Column("EntityID")]
    public int EntityId { get; set; }

    [ForeignKey("CaseId")]
    [InverseProperty("CaseEntities")]
    public virtual Case Case { get; set; }
    [ForeignKey(nameof(EntityId))]
    [InverseProperty("CaseEntities")]
    public virtual Entity Entity { get; set; }
}