// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("CASE_WORKFLOW", Schema = "algo")]
[Index("CaseId", Name = "FK_CASE_WORKFLOW_CaseID")]
public partial class CaseWorkflow
{
    [Key]
    [Column("CaseWorkFlowID")]
    public int CaseWorkFlowId { get; set; }

    [Column("CaseID")]
    public int CaseId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CaseWorkFlowDateTime { get; set; }

    [Column("BussinesProcessStepID")]
    public short BussinesProcessStepId { get; set; }

    [Column("CaseStatusID")]
    public byte CaseStatusId { get; set; }

    [Column("RoleID")]
    public short? RoleId { get; set; }

    [Column("AccountID")]
    public short? AccountId { get; set; }

    [Column(TypeName = "date")]
    public DateTime CaseResolutionDate { get; set; }

    public string CaseWorkflowComment { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("CaseWorkflows")]
    public virtual Account Account { get; set; }

    [ForeignKey("BussinesProcessStepId")]
    [InverseProperty("CaseWorkflows")]
    public virtual BusinessProcessStep BussinesProcessStep { get; set; }

    [ForeignKey("CaseId")]
    [InverseProperty("CaseWorkflows")]
    public virtual Case Case { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("CaseWorkflows")]
    public virtual Role Role { get; set; }
}