// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("DOCUMENT_WORKFLOW", Schema = "algo")]
[Index("DocumentId", Name = "FK_DOCUMENT_WORKFLOW_DocumentID")]
public partial class DocumentWorkflow
{
    [Key]
    [Column("DocumentWorkFlowID")]
    public int DocumentWorkFlowId { get; set; }

    [Column("DocumentID")]
    public int DocumentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DocumentWorkFlowDateTime { get; set; }

    [Column("BussinesProcessStepID")]
    public short BussinesProcessStepId { get; set; }

    [Column("DocumentStatusID")]
    public byte DocumentStatusId { get; set; }

    [Column("RoleID")]
    public short? RoleId { get; set; }

    [Column("AccountID")]
    public short? AccountId { get; set; }

    public byte? DocumentSignOrder { get; set; }

    public string DocumentWorkflowComment { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }
    public bool IsDeleted { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("DocumentWorkflows")]
    public virtual Account Account { get; set; }

    [ForeignKey("BussinesProcessStepId")]
    [InverseProperty("DocumentWorkflows")]
    public virtual BusinessProcessStep BussinesProcessStep { get; set; }

    [ForeignKey("DocumentId")]
    [InverseProperty("DocumentWorkflows")]
    public virtual Document Document { get; set; }
}