// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("DOCUMENT", Schema = "algo")]
[Index("DocumentRefNumber", Name = "AK_DOCUMENT", IsUnique = true)]
[Index("AccountId", Name = "FK_DOCUMENT_AccountID")]
[Index("DocumentStatusId", Name = "FK_DOCUMENT_DocumentStatusID")]
[Index("TemplateId", Name = "FK_DOCUMENT_TemplateID")]
[Index("CaseId", "DocumentCreatedDate", Name = "IX_DOCUMENT_1", IsDescending = new[] { false, true })]
[Index("CaseId", "DocumentId", Name = "IX_DOCUMENT_2")]
public partial class Document
{
    [Key]
    [Column("DocumentID")]
    public int DocumentId { get; set; }

    [Column("DocumentTypeID")]
    public byte DocumentTypeId { get; set; }

    [Column("DocumentStatusID")]
    public byte DocumentStatusId { get; set; }

    [Column("AccountID")]
    public short AccountId { get; set; }

    [Column("TemplateID")]
    public short? TemplateId { get; set; }

    [Column("CaseID")]
    public int CaseId { get; set; }

    [Required]
    [StringLength(150)]
    public string DocumentTitle { get; set; }

    [Required]
    [StringLength(255)]
    public string DocumentDesription { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DocumentCreatedDate { get; set; }

    [Required]
    public string DocumentRefNumber { get; set; }

    [Required]
    [StringLength(255)]
    public string DocumentUrl { get; set; }

    [Required]
    [StringLength(500)]
    public string DocumentComment { get; set; }

    public bool IsMailSent { get; set; }

    [Column("IsFileSent2DMS")]
    public bool IsFileSent2Dms { get; set; }

    public bool IsConfidential { get; set; }

    public bool IsMustSign { get; set; }

    public bool IsValidForm { get; set; }

    public bool Is4Send { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public bool IsMerged { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Documents")]
    public virtual Account Account { get; set; }

    [ForeignKey("CaseId")]
    [InverseProperty("Documents")]
    public virtual Case Case { get; set; }

    [InverseProperty("Document")]
    public virtual ICollection<DocumentParticipantProcess> DocumentParticipantProcesses { get; set; } = new List<DocumentParticipantProcess>();

    [InverseProperty("Document")]
    public virtual ICollection<DocumentWorkflow> DocumentWorkflows { get; set; } = new List<DocumentWorkflow>();

    [ForeignKey("TemplateId")]
    [InverseProperty("Documents")]
    public virtual Template Template { get; set; }
    [InverseProperty("Document")]
    public virtual ICollection<DocumentVersion> DocumentVersions { get; set; } = new List<DocumentVersion>();
}