// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("DOCUMENT_PARTICIPANT_PROCESS", Schema = "algo")]
[Index("AccountId", Name = "IX_DOCUMENT_PARTICIPANT_PROCESS_AccountID")]
[Index("DocumentId", Name = "IX_DOCUMENT_PARTICIPANT_PROCESS_DocumentID")]
public partial class DocumentParticipantProcess
{
    [Key]
    [Column("DocumentParticipantProcessID")]
    public int DocumentParticipantProcessId { get; set; }   

    [Column("DocumentID")]
    public int DocumentId { get; set; }

    [Column("AccountID")]
    public short AccountId { get; set; }

    [Column("RoleID")]
    public short RoleId { get; set; }   

    [Column(TypeName = "datetime")]
    public DateTime DefinitionDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiredDate { get; set; }

    public byte ApprovalOrder { get; set; }

    [StringLength(255)]
    public string CommentNote { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string SignType { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("DocumentParticipantProcesses")]
    public virtual Account Account { get; set; }

    [ForeignKey("DocumentId")]
    [InverseProperty("DocumentParticipantProcesses")]
    public virtual Document Document { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("DocumentParticipantProcesses")]
    public virtual Role Role { get; set; }  
}