// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities
{
    [Table("ENTITY_INDIVIDUAL", Schema = "ent")]
    [Index(nameof(Jmbg), Name = "AK_PERSON_ENTITY", IsUnique = true)]
    [Index(nameof(LastName), nameof(FirstName), Name = "IX_PERSON_ENTITY")]
    public partial class EntityIndividual
    {
        [Key]
        [Column("EntityID")]
        public int EntityId { get; set; }
        [Required]
        [Column("JMBG")]
        [StringLength(13)]
        public string Jmbg { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required]
        [StringLength(50)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(50)]
        public string TelephoneNo { get; set; }
        [Required]
        [StringLength(150)]
        public string Address { get; set; }
        [Required]
        [StringLength(30)]
        public string City { get; set; }
        [Required]
        [Column("ZIP")]
        [StringLength(5)]
        public string Zip { get; set; }
        [Required]
        [StringLength(50)]
        public string InsertUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDate { get; set; }
        [StringLength(50)]
        public string UpdateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey(nameof(EntityId))]
        [InverseProperty("EntityIndividual")]
        public virtual Entity Entity { get; set; }
    }
}