// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities
{
    [Table("ENTITY_TYPE", Schema = "ent")]
    public partial class EntityType
    {
        public EntityType()
        {
            Entities = new HashSet<Entity>();
        }

        [Key]
        [Column("EntityTypeID")]
        public byte EntityTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string EntityTypeNameLat { get; set; }
        [Required]
        [StringLength(50)]
        public string EntityTypeNameCyr { get; set; }
        [Required]
        [StringLength(50)]
        public string EntityTypeNameEng { get; set; }

        [InverseProperty(nameof(Entity.EntityType))]
        public virtual ICollection<Entity> Entities { get; set; }
    }
}