// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities
{
    [Table("ENTITY_LEGAL", Schema = "ent")]
    [Index(nameof(CustomerId), nameof(Pib), Name = "AK_ENTITY_LEGAL_CustomerID_PIB", IsUnique = true)]
    [Index(nameof(Name), Name = "IX_LEGAL_ENTITY_Name")]
    [Index(nameof(Pib), Name = "IX_LEGAL_ENTITY_PIB")]
    public partial class EntityLegal
    {
        [Key]
        [Column("EntityID")]
        public int EntityId { get; set; }
        [Required]
        [Column("PIB")]
        [StringLength(9)]
        public string Pib { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(50)]
        public string TelephoneNo { get; set; }
        [Required]
        [StringLength(150)]
        public string Address { get; set; }
        [Required]
        [StringLength(30)]
        public string City { get; set; }
        [Required]
        [Column("ZIP")]
        [StringLength(5)]
        public string Zip { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Required]
        [StringLength(50)]
        public string InsertUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDate { get; set; }
        [StringLength(50)]
        public string UpdateUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey(nameof(EntityId))]
        [InverseProperty("EntityLegal")]
        public virtual Entity Entity { get; set; }
    }
}