// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("SERVICE_DEF", Schema = "algo")]
[Index("ServiceId", "BusinessProcessId", "TemplateId", "RoleId", Name = "AK_SERVICE_DEF", IsUnique = true)]
[Index("BusinessProcessId", Name = "FK_SERVICE_DEF_BusinessProcessID")]
[Index("RoleId", Name = "FK_SERVICE_DEF_RoleID")]
[Index("ServiceId", Name = "FK_SERVICE_DEF_ServiceID")]
[Index("TemplateId", Name = "FK_SERVICE_DEF_TemplateID")]
public partial class ServiceDef
{
    [Key]
    [Column("ServiceDefID")]
    public short ServiceDefId { get; set; }

    [Column("ServiceID")]
    public short ServiceId { get; set; }

    [Column("BusinessProcessID")]
    public short BusinessProcessId { get; set; }

    [Column("TemplateID")]
    public short TemplateId { get; set; }

    [Column("RoleID")]
    public short RoleId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("BusinessProcessId")]
    [InverseProperty("ServiceDefs")]
    public virtual BusinessProcess BusinessProcess { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("ServiceDefs")]
    public virtual Role Role { get; set; }

    [ForeignKey("TemplateId")]
    [InverseProperty("ServiceDefs")]
    public virtual Template Template { get; set; }
}