// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("TEMPLATE_SIGN", Schema = "algo")]
[Index("TemplateId", Name = "IX_TEMPLATE_SIGN_TemplateID")]
public partial class TemplateSign
{
    [Key]
    [Column("TemplateSignID")]
    public short TemplateSignId { get; set; }

    [Column("TemplateID")]
    public short TemplateId { get; set; }

    [Column("TemplateSignTypeID")]
    public byte TemplateSignTypeId { get; set; }

    public byte SignPageNumber { get; set; }

    [Column("SignXPosition")]
    public short SignXposition { get; set; }

    [Column("SignYPosition")]
    public short SignYposition { get; set; }

    public short SignWidth { get; set; }

    public short SignHeight { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int DigitalSignType { get; set; }

    [ForeignKey("TemplateId")]
    [InverseProperty("TemplateSigns")]
    public virtual Template Template { get; set; }

    [InverseProperty("TemplateSign")]
    public virtual ICollection<TemplateSignPosition> TemplateSignPositions { get; set; } = new List<TemplateSignPosition>();

    [ForeignKey("TemplateSignTypeId")]
    [InverseProperty("TemplateSigns")]
    public virtual TemplateSignType TemplateSignType { get; set; }
}