// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;
[PrimaryKey("TemplateId", "RoleId", "ApprovalOrder")]
[Table("TEMPLATE_ROLE_APPROVAL_ORDER", Schema = "algo")]
public partial class TemplateRoleApprovalOrder
{
    [Key]
    [Column("TemplateID")]
    public short TemplateId { get; set; }

    [Key]
    [Column("RoleID")]
    public short RoleId { get; set; }

    [Key]
    public byte ApprovalOrder { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime InsertDate { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? UpdateDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }
}