// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("TEMPLATE_SIGN_TYPE", Schema = "algo")]
public partial class TemplateSignType
{
    [Key]
    [Column("TemplateSignTypeID")]
    public byte TemplateSignTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string TemplateSignTypeNameCyr { get; set; }

    [Required]
    [StringLength(50)]
    public string TemplateSignTypeNameLat { get; set; }

    [Required]
    [StringLength(50)]
    public string TemplateSignTypeNameEng { get; set; }

    [Required]
    [StringLength(100)]
    public string TemplateSignTypeNameDesc { get; set; }

    public bool TemplateSignTypeIsEnabled { get; set; }

    [InverseProperty("TemplateSignType")]
    public virtual ICollection<TemplateSign> TemplateSigns { get; set; } = new List<TemplateSign>();
}