// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("TEMPLATE", Schema = "algo")]
[Index("TemplateCode", Name = "AK_TEMPLATE", IsUnique = true)]
[Index("CaseClasificationId", Name = "FK_TEMPLATE_CaseClasificationID")]
[Index("TemplateStatusId", Name = "FK_TEMPLATE_TemplateStatusID")]
[Index("TemplateTypeId", Name = "FK_TEMPLATE_TemplateTypeID")]
public partial class Template
{
    [Key]
    [Column("TemplateID")]
    public short TemplateId { get; set; }

    [Column("TemplateTypeID")]
    public short TemplateTypeId { get; set; }

    public bool IsApplicationForm { get; set; }

    [Required]
    [StringLength(18)]
    public string TemplateCode { get; set; }

    [Required]
    [StringLength(150)]
    public string TemplateNameLat { get; set; }

    [StringLength(150)]
    public string TemplateNameCyr { get; set; }

    [StringLength(150)]
    public string TemplateNameEng { get; set; }

    [Required]
    [StringLength(500)]
    public string TemplateDescription { get; set; }

    [Required]
    [Column("TemplateURL")]
    [StringLength(255)]
    [Unicode(false)]
    public string TemplateUrl { get; set; }

    [Column("TemplateStatusID")]
    public byte TemplateStatusId { get; set; }

    public bool Is4Send { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime TemplateCreatedDate { get; set; }

    [Required]
    [Column("CaseClasificationID")]
    [StringLength(10)]
    [Unicode(false)]
    public string CaseClasificationId { get; set; }

    [Column("LKRM")]
    public short Lkrm { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? TemplateUpdateDate { get; set; }

    [Column("EntityTypeID")]
    public byte EntityTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [Column("LanguageCountryID")]
    public byte LanguageCountryId { get; set; }

    [InverseProperty("Template")]
    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    [InverseProperty("Template")]
    public virtual ICollection<ServiceDef> ServiceDefs { get; set; } = new List<ServiceDef>();

    [InverseProperty("Template")]
    public virtual ICollection<TemplateSign> TemplateSigns { get; set; } = new List<TemplateSign>();

    [ForeignKey("TemplateTypeId")]
    [InverseProperty("Templates")]
    public virtual TemplateType TemplateType { get; set; }
}