// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DocumentManagement.Rest.Api.Entities;

[Table("TEMPLATE_SIGN_POSITION", Schema = "algo")]
public partial class TemplateSignPosition
{
    [Key]
    [Column("TemplateSignPositionID")]
    public short TemplateSignPositionId { get; set; }

    public byte SignPageNumber { get; set; }

    [Column("SignXPosition")]
    public short SignXposition { get; set; }

    [Column("SignYPosition")]
    public short SignYposition { get; set; }

    public short SignWidth { get; set; }

    public short SignHeight { get; set; }

    [Column("TemplateSignID")]
    public short TemplateSignId { get; set; }

    [StringLength(50)]
    public string SignRole { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string InsertUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InsertDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("TemplateSignId")]
    [InverseProperty("TemplateSignPositions")]
    public virtual TemplateSign TemplateSign { get; set; }
}